image: centos8-dev:2.0

stages:
  - build
  - test
  - deploy

# 构建阶段
build_job:
  stage: build
  tags:
    - local
  script:
    - echo "Building the app..."
#   - gradle build

# 测试阶段
test_job:
  stage: test
  tags:
    - local
  script:
    - echo "Running tests..."
#    - gradle test

# 部署阶段
deploy_job:
  stage: deploy
  tags:
    - local
  script:
    - echo "Deploying the app..."
    - gradle myPushImage
  only:
    - master  # 只在master分支上进行部署
  artifacts:
    paths:
     #会把build/libs/springboot340Test-0.0.1.jar压缩成artifacts.zip
      - build/libs/springboot340Test-0.0.1.jar
