stages:
  - build
  - test
  - deploy

# 构建阶段
build_job:
  stage: build
  tags:
    - local
  script:
    - echo "Building the app..."
    - gradle build

# 测试阶段
test_job:
  stage: test
  tags:
    - local
  script:
    - echo "Running tests..."
    - gradle build

# 部署阶段
deploy_job:
  stage: deploy
  tags:
    - local
  script:
    - echo "Deploying the app..."
    -  gradle bootJar
  only:
    - master  # 只在master分支上进行部署
